export const CITIES = [
  { code: "DAC", name: "Dhaka", country: "Bangladesh" },
  { code: "DEL", name: "New Delhi", country: "India" },
  { code: "DXB", name: "Dubai", country: "UAE" },
  { code: "LHR", name: "London", country: "United Kingdom" },
  { code: "JFK", name: "New York", country: "USA" },
  { code: "SIN", name: "Singapore", country: "Singapore" },
  { code: "HKG", name: "Hong Kong", country: "Hong Kong" },
  { code: "BKK", name: "Bangkok", country: "Thailand" },
  { code: "CDG", name: "Paris", country: "France" },
  { code: "FRA", name: "Frankfurt", country: "Germany" },
  { code: "AMS", name: "Amsterdam", country: "Netherlands" },
  { code: "IST", name: "Istanbul", country: "Turkey" },
  { code: "DOH", name: "Doha", country: "Qatar" },
  { code: "KUL", name: "Kuala Lumpur", country: "Malaysia" },
  { code: "SYD", name: "Sydney", country: "Australia" },
]

export const DUMMY_FLIGHTS = [
  {
    id: "1",
    airline: "Emirates",
    flightNumber: "EK 582",
    departure: { time: "10:30 AM", airport: "DAC" },
    arrival: { time: "2:45 PM", airport: "DXB" },
    duration: "4h 15m",
    stops: 0,
    price: 850,
    class: "Economy",
  },
  {
    id: "2",
    airline: "Qatar Airways",
    flightNumber: "QR 639",
    departure: { time: "11:00 AM", airport: "DAC" },
    arrival: { time: "3:30 PM", airport: "DOH" },
    duration: "4h 30m",
    stops: 0,
    price: 920,
    class: "Economy",
  },
  {
    id: "3",
    airline: "Singapore Airlines",
    flightNumber: "SQ 447",
    departure: { time: "1:15 PM", airport: "DAC" },
    arrival: { time: "7:45 PM", airport: "SIN" },
    duration: "6h 30m",
    stops: 1,
    price: 650,
    class: "Economy",
  },
  {
    id: "4",
    airline: "Etihad Airways",
    flightNumber: "EY 211",
    departure: { time: "2:00 PM", airport: "DAC" },
    arrival: { time: "6:15 PM", airport: "DXB" },
    duration: "4h 15m",
    stops: 0,
    price: 895,
    class: "Economy",
  },
  {
    id: "5",
    airline: "Lufthansa",
    flightNumber: "LH 760",
    departure: { time: "3:45 PM", airport: "DAC" },
    arrival: { time: "11:30 PM", airport: "FRA" },
    duration: "11h 45m",
    stops: 1,
    price: 1150,
    class: "Economy",
  },
  {
    id: "6",
    airline: "Emirates",
    flightNumber: "EK 584",
    departure: { time: "5:30 PM", airport: "DAC" },
    arrival: { time: "9:45 PM", airport: "DXB" },
    duration: "4h 15m",
    stops: 0,
    price: 875,
    class: "Business",
  },
]
